---
title: "jenny_hotelbookings"
author: "Jenny Yu"
date: "2/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
hotel_bookings <- read.csv("hotel_bookings.csv")
summary(hotel_bookings)

# factor needed variables
hotel_bookings$is_repeated_guest <- as.factor(hotel_bookings$is_repeated_guest)
hotel_bookings$company <- as.factor(hotel_bookings$company)
hotel_bookings$hotel <- as.factor(hotel_bookings$hotel)
hotel_bookings$arrival_date_month <- as.factor(hotel_bookings$arrival_date_month)
hotel_bookings$arrival_date_year <- as.factor(hotel_bookings$arrival_date_year)
hotel_bookings$meal <- as.factor(hotel_bookings$meal)
hotel_bookings$country <- as.factor(hotel_bookings$country)
hotel_bookings$market_segment <- as.factor(hotel_bookings$market_segment)
hotel_bookings$distribution_channel <- as.factor(hotel_bookings$distribution_channel)
hotel_bookings$reserved_room_type <- as.factor(hotel_bookings$reserved_room_type)
hotel_bookings$assigned_room_type <- as.factor(hotel_bookings$assigned_room_type)
hotel_bookings$agent <- as.factor(hotel_bookings$agent)
hotel_bookings$reservation_status_date <- as.factor(hotel_bookings$reservation_status_date)
hotel_bookings$reservation_status <- as.factor(hotel_bookings$reservation_status)
hotel_bookings$customer_type <- as.factor(hotel_bookings$customer_type)
hotel_bookings$deposit_type <- as.factor(hotel_bookings$deposit_type)

head(hotel_bookings)
summary(hotel_bookings)

str(hotel_bookings)

```



#number of customers and effect on cancellations
```{r}
hotel_bookings$total_guests <- hotel_bookings$adults + hotel_bookings$children + hotel_bookings$babies

summary(hotel_bookings$total_guests, na.rm=TRUE)

cancelratebyadults <- aggregate(is_canceled ~ adults, data=hotel_bookings, mean)

cancelratebyguests <- aggregate(is_canceled ~ total_guests, data=hotel_bookings, mean)

barplot(cancelratebyadults$is_canceled, col=cancelratebyadults$adults, names.arg = cancelratebyadults$adults, xlab="Total Number of Adults", ylab="Cancellation Rate", border =TRUE, axes= TRUE, ylim=c(0,1))

barplot(cancelratebyguests$is_canceled, col=cancelratebyguests$total_guests, names.arg = cancelratebyguests$total_guests, xlab="Total Number of Guests", ylab="Cancellation Rate", border =TRUE, axes= TRUE, ylim=c(0,1))

```

## Previous Cancellations
```{r}
hotel_bookings$previous_cancellations
 
cancelratebyprevcancellations <- aggregate(is_canceled ~ previous_cancellations, data=hotel_bookings, mean)

barplot(cancelratebyprevcancellations$is_canceled, col=cancelratebyprevcancellations$previous_cancellations, names.arg = cancelratebyprevcancellations$previous_cancellations, xlab="Total Number of Previous Cancellations", ylab="Cancellation Rate", border =TRUE, axes= TRUE, ylim=c(0,1))
```


##corporate vs no
```{r}
hotel_bookings$corporateornot <- ifelse(hotel_bookings$distribution_channel == "Corporate", "Corporate", "No")

cancelratebycorporate <- aggregate(is_canceled ~ corporateornot, data=hotel_bookings, mean)

barplot(cancelratebycorporate$is_canceled, col=c("red","blue"), names.arg = cancelratebycorporate$corporateornot, xlab="Booking Type", ylab="Cancellation Rate", border =TRUE, axes= TRUE, ylim=c(0,1))


```

## Meal
```{r}
mealeffect <- tapply(hotel_bookings$is_canceled, hotel_bookings$meal, mean, na.rm = TRUE)
barplot(sort(mealeffect), ylim = c(0,1), col=c("lavenderblush","pink","hotpink", "deeppink", "deeppink4"), xlab="Meal Plan Option", ylab="Cancellation Rate")
```

## Reserved Room Type
```{r}
reservedroomtype <- tapply(hotel_bookings$is_canceled, hotel_bookings$reserved_room_type, mean, na.rm = TRUE)
barplot(sort(reservedroomtype), ylim = c(0,1), col=c("lavenderblush","pink","hotpink", "deeppink", "deeppink4"), xlab="Reserved Room Type", ylab="Cancellation Rate")

```

## Is Repeated Guest
```{r}
repeatedguest <- tapply(hotel_bookings$is_canceled, hotel_bookings$is_repeated_guest, mean, na.rm = TRUE)
barplot(sort(repeatedguest), ylim = c(0,1), col=c("lavenderblush","pink","hotpink", "deeppink", "deeppink4"), names.arg = c("Yes", "No"), xlab="Are They A Repeated Guest?", ylab="Cancellation Rate")
```


## Distribution Channel
```{r}
distchannel <- tapply(hotel_bookings$is_canceled, hotel_bookings$distribution_channel, mean, na.rm = TRUE)
barplot(sort(distchannel), ylim = c(0,1), col=c("red","blue","green", "pink", "yellow"), xlab="Distribution Channel", ylab = "Cancellation Rate")


```

