---
title: "StrokeDataJY"
author: "Jenny Yu"
date: "4/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load and Clean Data
```{r}
stroke <- read.csv("healthcare-dataset-stroke-data.csv")
stroke <- stroke[stroke$gender != "Other",]
stroke$id <- NULL
stroke$gender <- as.factor(stroke$gender)
stroke$work_type <- as.factor(stroke$work_type)
stroke$smoking_status <- as.factor(stroke$smoking_status)
stroke$ever_married <- as.factor(stroke$ever_married)
stroke$Residence_type <- as.factor(stroke$Residence_type)
stroke$heart_disease <- as.factor(stroke$heart_disease)
stroke$bmi <- as.numeric(stroke$bmi)

summary(stroke)
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

strokemm <- as.data.frame(model.matrix(~.-1,stroke))
stroke_norm <- as.data.frame(lapply(strokemm, normalize))
summary(stroke_norm)
```

## Decision Tree
```{r}
library(C50)

set.seed(12345)
#25% ish in test, all others in train, for this choose round numbers - 1280 random in test, others in train
testrows <- sample(1:nrow(stroke),1280)
stroketrain <- stroke[-testrows, ]
stroketest <- stroke[testrows, ]

#rebalance errors - want to prioritize minimizing false negatives, if people are at risk of stroke we want to know
error_cost <- matrix(c(0, 1, 6, 0), nrow = 2)

#build decision tree
stroke_dt <- C5.0(as.factor(stroke) ~ ., data = stroketrain, costs = error_cost)

plot(stroke_dt)
summary(stroke_dt)

#predict the test data
stroke_dt_pred <- predict(stroke_dt, stroketest)
library(gmodels)
CrossTable(stroketest$stroke, stroke_dt_pred)

# Confusion Matrix and Kappa Statistics

library(caret)
library(class)


confusionMatrix(stroke_dt_pred, as.factor(stroketest$stroke))
```

## Decision Trees Based On Age
```{r}
#separate data set for further insights
ageYoung <- stroketrain[stroketrain$age <= 55,]
ageOld <- stroketrain[stroketrain$age > 55,]

ageYoungtest <- stroketest[stroketest$age <= 55,]
ageOldtest <- stroketest[stroketest$age > 55,]


#Young Patients
#rebalance errors - want to prioritize minimizing false negatives, if people are at risk of stroke we want to know
error_cost2 <- matrix(c(0, 1, 10, 0), nrow = 2)

ageYoung_dt <- C5.0(as.factor(stroke) ~ ., data = ageYoung, costs = error_cost2)
plot(ageYoung_dt)
summary(ageYoung_dt)

#predict the test data
ageYoung_dt_pred <- predict(ageYoung_dt, ageYoungtest)

CrossTable(ageYoungtest$stroke, ageYoung_dt_pred)

# Confusion Matrix and Kappa Statistics
confusionMatrix(ageYoung_dt_pred, as.factor(ageYoungtest$stroke))

#Old Patients
#rebalance errors - want to prioritize minimizing false negatives, if people are at risk of stroke we want to know
error_cost3 <- matrix(c(0, 1, 10, 0), nrow = 2)

ageOld_dt <- C5.0(as.factor(stroke) ~ ., data = ageOld, costs = error_cost3)
plot(ageOld_dt)
summary(ageOld_dt)

#predict the test data
ageOld_dt_pred <- predict(ageOld_dt, ageOldtest)

CrossTable(ageOldtest$stroke, ageOld_dt_pred)

# Confusion Matrix and Kappa Statistics
confusionMatrix(ageOld_dt_pred, as.factor(ageOldtest$stroke))

#Combined confusion matrix
combinedagepredict <- c(ageOld_dt_pred,ageYoung_dt_pred)-1
summary(combinedagepredict)

combinedageactual <- c(ageOldtest$stroke, ageYoungtest$stroke)
summary(combinedageactual)

confusionMatrix(as.factor(combinedagepredict), as.factor(combinedageactual))
```

## Decision Trees Based on BMI
```{r}
# separate data for further insight
bmiRisk <- stroketrain[stroketrain$bmi > 26.5 & stroketrain$bmi < 32,]
bmiNotRisk <- stroketrain[stroketrain$bmi <= 26.5 | stroketrain$bmi >= 32,]

bmiRisktest <- stroketest[stroketest$bmi > 26.5 & stroketest$bmi < 32,]
bmiNotRisktest <- stroketest[stroketest$bmi <= 26.5 | stroketest$bmi >= 32,]

summary(bmiRisk)

#Risky BMI Patients
#rebalance errors - want to prioritize minimizing false negatives, if people are at risk of stroke we want to know
error_cost4 <- matrix(c(0, 1, 10, 0), nrow = 2)

bmiRisk_dt <- C5.0(as.factor(stroke) ~ ., data = bmiRisk, costs = error_cost4)
plot(bmiRisk_dt)
summary(bmiRisk_dt)

#predict the test data
bmiRisk_dt_pred <- predict(bmiRisk_dt, bmiRisktest)

CrossTable(bmiRisktest$stroke, bmiRisk_dt_pred)

# Confusion Matrix and Kappa Statistics
confusionMatrix(bmiRisk_dt_pred, as.factor(bmiRisktest$stroke))

#Not Risky BMI Patients
#rebalance errors - want to prioritize minimizing false negatives, if people are at risk of stroke we want to know
error_cost5 <- matrix(c(0, 1, 10, 0), nrow = 2)

bmiNotRisk_dt <- C5.0(as.factor(stroke) ~ ., data = bmiNotRisk, costs = error_cost5)
plot(bmiNotRisk_dt)
summary(bmiNotRisk_dt)

#predict the test data
bmiNotRisk_dt_pred <- predict(bmiNotRisk_dt, bmiNotRisktest)

CrossTable(bmiNotRisktest$stroke, bmiNotRisk_dt_pred)

# Confusion Matrix and Kappa Statistics
confusionMatrix(bmiNotRisk_dt_pred, as.factor(bmiNotRisktest$stroke))

#Combined confusion matrix
combinedbmipredict <- c(bmiNotRisk_dt_pred,bmiRisk_dt_pred)-1
summary(combinedbmipredict)

combinedbmiactual <- c(bmiNotRisktest$stroke, bmiRisktest$stroke)
summary(combinedbmiactual)

confusionMatrix(as.factor(combinedbmipredict), as.factor(combinedbmiactual))
```

