---
title: "KNN Model"
author: "Xincheng Yuan"
date: "4/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Data Cleaning According to DataCreatio.R line 1-22
################### Read in data and remove NA
stroke <- read.csv("healthcare-dataset-stroke-data.csv")
stroke <- stroke[stroke$gender != "Other",]
stroke$id <- NULL
stroke$gender <- as.factor(stroke$gender)
stroke$work_type <- as.factor(stroke$work_type)
stroke$smoking_status <- as.factor(stroke$smoking_status)
stroke$ever_married <- as.factor(stroke$ever_married)
stroke$Residence_type <- as.factor(stroke$Residence_type)
summary(stroke)

# create the bmi data that doesn't have NA
bmi_data <- stroke[stroke$bmi != "N/A",]
# can't use stroke to predict bmi
bmi_model <- lm(bmi ~ .-stroke, data = bmi_data)
summary(bmi_model)
# remove insignificant variables
bmi_model <- lm(bmi ~ .-stroke-gender-Residence_type+age*hypertension*ever_married-heart_disease, data = bmi_data)
summary(bmi_model)

stroke$bmi[stroke$bmi == "N/A"] = predict(bmi_model, stroke[stroke$bmi == "N/A",])
stroke$bmi <- as.numeric(stroke$bmi)
```


```{r}
#Data. Creation Line 24-40

set.seed(42)

normalize <- function(x) {
  if(max(x) - min(x) == 0){
    return (x)
  }
  return ((x - min(x)) / (max(x) - min(x)))
}

set_splits <- function(x, norm) {
  if(norm){
    x = as.data.frame(lapply(as.data.frame(model.matrix(~.-1,x)), normalize))
  }
  testrows <- sample(1:nrow(x), 0.25*nrow(x))
  return (list(x[-testrows,], x[testrows,]))
}

# Split Data from DataCreation.r line 44-56

# you can access the dataframe with age_young_data[[1]] for train, age_young_data[[2]] for test
general <- set_splits(stroke, norm = FALSE)
age_young_data = set_splits(stroke[stroke$age<=55,], norm = FALSE)
age_old_data = set_splits(stroke[stroke$age>55,], norm = FALSE)
bmi_risk_data = set_splits(stroke[stroke$bmi>26.5 & stroke$bmi<32,], norm = FALSE)
bmi_safe_data = set_splits(stroke[stroke$bmi<=26.5 | stroke$bmi>=32,], norm = FALSE)

# alternatively do it with the norm; you'll only need one of the splits
general_norm <- set_splits(stroke, norm = TRUE)
age_young_data_norm = set_splits(stroke[stroke$age<=55,], norm = TRUE)
age_old_data_norm = set_splits(stroke[stroke$age>55,], norm = TRUE)
bmi_risk_data_norm = set_splits(stroke[stroke$bmi>26.5 & stroke$bmi<32,], norm = TRUE)
bmi_safe_data_norm = set_splits(stroke[stroke$bmi<=26.5 | stroke$bmi>=32,], norm = TRUE)
```


##KNN Model (General)
```{r}
set.seed(12345)
stroketrain_knn <- general_norm[[1]]
stroketest_knn <- general_norm[[2]]

knn_train_labels <- general_norm[[1]]$stroke
knn_test_labels <- general_norm[[2]]$stroke

library(class)
library(caret)
stroke_knn_test_pred <- knn(train = stroketrain_knn, test = stroketest_knn,
                      cl = knn_train_labels, k= sqrt(sqrt(nrow(general_norm[[1]]))))

confusionMatrix(as.factor(stroke_knn_test_pred), as.factor(knn_test_labels))
```

##KNN Model (split by age)
```{r}
library(class)
library(caret)

###Young patients
stroketrain_knn_young <- age_young_data_norm[[1]]
stroketest_knn_young <- age_young_data_norm[[2]]
knn_train_labels_young <- age_young_data_norm[[1]]$stroke
knn_test_labels_young <- age_young_data_norm[[2]]$stroke

stroke_knn_pred_young <- knn(train = stroketrain_knn_young, test = stroketest_knn_young,
                      cl = knn_train_labels_young, k= sqrt(sqrt(nrow(stroketrain_knn_young))))
confusionMatrix(as.factor(stroke_knn_pred_young), as.factor(knn_test_labels_young))

###Old patients
stroketrain_knn_old <- age_old_data_norm[[1]]
stroketest_knn_old <- age_old_data_norm[[2]]
knn_train_labels_old <- age_old_data_norm[[1]]$stroke
knn_test_labels_old <- age_old_data_norm[[2]]$stroke

stroke_knn_pred_old <- knn(train = stroketrain_knn_old, test = stroketest_knn_old,
                      cl = knn_train_labels_old, k = sqrt(sqrt(nrow(stroketrain_knn_old))))
confusionMatrix(as.factor(stroke_knn_pred_old), as.factor(knn_test_labels_old))

##Combined
knn_age_combined_pred = c(stroke_knn_pred_young, stroke_knn_pred_old) - 1
true_label_age = c(age_young_data_norm[[2]]$stroke, age_old_data_norm[[2]]$stroke)
confusionMatrix(as.factor(knn_age_combined_pred), as.factor(true_label_age))

```

##KNN Model (split by BMI)
```{r}
library(class)
library(caret)

###Risky patients
stroketrain_knn_risk <- bmi_risk_data_norm[[1]]
stroketest_knn_risk <- bmi_risk_data_norm[[2]]
knn_train_labels_risk <- bmi_risk_data_norm[[1]]$stroke
knn_test_labels_risk <- bmi_risk_data_norm[[2]]$stroke

stroke_knn_pred_risk <- knn(train = stroketrain_knn_risk, test = stroketest_knn_risk,
                      cl = knn_train_labels_risk, k= sqrt(sqrt(nrow(stroketrain_knn_risk))))
confusionMatrix(as.factor(stroke_knn_pred_risk), as.factor(knn_test_labels_risk))

###Safe patients
stroketrain_knn_safe <- bmi_safe_data_norm[[1]]
stroketest_knn_safe <- bmi_safe_data_norm[[2]]
knn_train_labels_safe <- bmi_safe_data_norm[[1]]$stroke
knn_test_labels_safe <- bmi_safe_data_norm[[2]]$stroke

stroke_knn_pred_safe <- knn(train = stroketrain_knn_safe, test = stroketest_knn_safe,
                      cl = knn_train_labels_safe, k = sqrt(sqrt(nrow(stroketrain_knn_safe))))
confusionMatrix(as.factor(stroke_knn_pred_safe), as.factor(knn_test_labels_safe))

##Combined
knn_bmi_combined_pred = c(stroke_knn_pred_risk, stroke_knn_pred_safe) - 1
true_label_bmi = c(bmi_risk_data_norm[[2]]$stroke, bmi_safe_data_norm[[2]]$stroke)
confusionMatrix(as.factor(knn_bmi_combined_pred), as.factor(true_label_bmi))
```