---
title: "Logit Model"
author: "Evan Jiang"
date: "4/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Reading the data
```{r}
stroke <- read.csv("healthcare-dataset-stroke-data.csv")
stroke <- stroke[stroke$gender != "Other",]
stroke$id <- NULL
stroke$gender <- as.factor(stroke$gender)
stroke$work_type <- as.factor(stroke$work_type)
stroke$smoking_status <- as.factor(stroke$smoking_status)
stroke$ever_married <- as.factor(stroke$ever_married)
stroke$Residence_type <- as.factor(stroke$Residence_type)
stroke$heart_disease <- as.factor(stroke$heart_disease)
stroke$bmi <- as.numeric(stroke$bmi)


# create the bmi data that doesn't have NA
bmi_data <- stroke[!is.na(stroke$bmi),]
# can't use stroke to predict bmi
bmi_model <- lm(bmi ~ .-stroke, data = bmi_data)
# remove insignificant variables
bmi_model <- lm(bmi ~ .-stroke-gender-Residence_type+age*hypertension*ever_married-heart_disease, data = bmi_data)

stroke$bmi[is.na(stroke$bmi)] = predict(bmi_model, stroke[is.na(stroke$bmi),])


normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

strokemm <- as.data.frame(model.matrix(~.-1,stroke))
stroke_norm <- as.data.frame(lapply(strokemm, normalize))
```
## Create test and train split
```{r}
set.seed(12345)
#25% ish in test, all others in train, for this choose round numbers - 1280 random in test, others in train
testrows <- sample(1:nrow(stroke_norm),1280)
stroketrainLOG <- stroke_norm[-testrows, ]
stroketestLOG <- stroke_norm[testrows, ]
```


## Logit Model 
```{r}
library(gmodels)
library(caret)
library(class)

#Mass Effect
MassEffect <- glm(stroke ~ ., data = stroketrainLOG, family = "binomial")
summary(MassEffect)

#Final
logit_final <- step(MassEffect)
summary(logit_final)
```

## Cross table
```{r}
LogReg_Pred = predict(logit_final, newdata = stroketestLOG, type = "response")
LogReg_Pred = ifelse(LogReg_Pred>.11, 1, 0)
CrossTable(x = stroketestLOG$stroke, y = LogReg_Pred, prop.chisq=FALSE)
confusionMatrix(data = as.factor(LogReg_Pred), reference = as.factor(stroketestLOG$stroke))
#.11 gave the highest kappa statistic

```

## Age and BMI Data Loading and Splitting
```{r}
set.seed(42)

normalize <- function(x) {
  if(max(x) - min(x) == 0){
    return (x)
  }
  return ((x - min(x)) / (max(x) - min(x)))
}

set_splits <- function(x, norm) {
  if(norm){
    x = as.data.frame(lapply(as.data.frame(model.matrix(~.-1,x)), normalize))
  }
  testrows <- sample(1:nrow(x), 0.25*nrow(x))
  return (list(x[-testrows,], x[testrows,]))
}

general_norm <- set_splits(stroke, norm = TRUE)
age_young_data_norm = set_splits(stroke[stroke$age<=55,], norm = TRUE)
age_old_data_norm = set_splits(stroke[stroke$age>55,], norm = TRUE)
bmi_risk_data_norm = set_splits(stroke[stroke$bmi>26.5 & stroke$bmi<32,], norm = TRUE)
bmi_safe_data_norm = set_splits(stroke[stroke$bmi<=26.5 | stroke$bmi>=32,], norm = TRUE)
```

## Age Split Models
```{r}
#Young
masslogmodel_young <- glm(stroke ~., data = age_young_data_norm[[1]], family = "binomial")
summary(masslogmodel_young)

finallogmodel_young <- step(masslogmodel_young)
summary(finallogmodel_young)

young_Logpred <- predict(finallogmodel_young, age_young_data_norm[[2]], type= "response")
young_Logpred = ifelse(young_Logpred>0, 0, 1)

#Old
masslogmodel_old <- glm(stroke ~., data = age_old_data_norm[[1]], family = "binomial")
summary(masslogmodel_old)

finallogmodel_old <- step(masslogmodel_old)
summary(finallogmodel_old)

old_Logpred <- predict(finallogmodel_old, age_old_data_norm[[2]], type= "response")
old_Logpred = ifelse(old_Logpred>0, 0, 1)

#Combine Predictions
age_combined_Logpred = c(young_Logpred, old_Logpred)

age_true_label = c(age_young_data_norm[[2]]$stroke, age_old_data_norm[[2]]$stroke)

confusionMatrix(as.factor(age_combined_Logpred), as.factor(age_true_label))
summary(young_Logpred)
summary(old_Logpred)
summary(age_combined_Logpred)
```

## BMI Split Models
```{r}
#Risk
masslogmodel_risk <- glm(stroke ~., data = bmi_risk_data_norm[[1]], family = "binomial")
summary(masslogmodel_risk)

finallogmodel_risk <- step(masslogmodel_risk)
summary(finallogmodel_risk)

risk_Logpred <- predict(finallogmodel_risk, bmi_risk_data_norm[[2]], type= "response")
risk_Logpred = ifelse(risk_Logpred>.4, 0, 1)

#Safe
masslogmodel_safe <- glm(stroke ~., data = bmi_safe_data_norm[[1]], family = "binomial")
summary(masslogmodel_safe)

finallogmodel_safe <- step(masslogmodel_safe)
summary(finallogmodel_safe)

safe_Logpred <- predict(finallogmodel_safe, bmi_safe_data_norm[[2]], type= "response")
safe_Logpred = ifelse(safe_Logpred>.0004, 0, 1)

#Combine Predictions
bmi_combined_Logpred = c(risk_Logpred, safe_Logpred)

bmi_true_label = c(bmi_risk_data_norm[[2]]$stroke, bmi_safe_data_norm[[2]]$stroke)

confusionMatrix(as.factor(bmi_combined_Logpred), as.factor(bmi_true_label))
summary(risk_Logpred)
summary(safe_Logpred)



```


